main/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('all-news',views.all_news,name='all-news'),
    path('all-teachers',views.all_teachers,name='all-teachers'),
    path('all-students',views.all_students,name='all-students'),
    path('faoliyat',views.faoliyat,name='faoliyat'),
    path('kafedra',views.kafedra,name='kafedra'),
    path('detail/<int:id>',views.detail,name="detail"),
    path('contact',views.contact,name = "contact"),
    # path('category/<int:id>',views.category,name='category'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
] 

main/models.py
from django.db import models

# category model
class Category(models.Model):
    title=models.CharField(max_length=200)
    category_image=models.ImageField(upload_to='imgs/')

    class Meta:
        verbose_name_plural ='Categories'

    def __str__(self):
        return self.title

# News model
class News(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    image=models.ImageField(upload_to='Imgs')
    detail=models.TextField()
    add_time=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural ='News'

    def __str__(self):
        return self.title
    
# comments Model

class Comment(models.Model):
    news=models.ForeignKey(News,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    email=models.EmailField()
    comment=models.TextField()
    status=models.BooleanField(default=False)

    def __str__(self):
        return self.comment 
    
# Contact Model
class Contact(models.Model):
    full_name = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    full_text = models.CharField(max_length=400)
    phone=models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    
    
# Teacher Model
class Teacher(models.Model):
    full_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='Imgs')
    bio = models.CharField(max_length = 200)
    pthone_number = models.CharField(max_length=30)
    
    class Meta:
        verbose_name_plural ='Teachers'

    def __str__(self):
        return self.full_name
    
        
# Student Model
class Student(models.Model):
    full_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='Imgs')
    bio = models.CharField(max_length = 200)
    pthone_number = models.CharField(max_length=30)
    
    class Meta:
        verbose_name_plural ='Students'

    def __str__(self):
        return self.full_name
    
    
    

main/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import News,Category,Comment,Contact,Teacher,Student

#  Home Page
def home(request):
    first_news=News.objects.first()
    three_news=News.objects.all()[1:4]
    three_categories=Category.objects.all()[0:3]

    return render(request, 'home.html',{
        'first_news':first_news,
        'three_news':three_news,
        'three_categories':three_categories
    })
    
def home_2(request):
    all_teachers=Teacher.objects.all()
    return render(request, 'home.html',{
        'all_teachers':all_teachers
    })

# All News Page
def all_news(request):
    all_news=News.objects.all()
    return render(request, 'all-news.html',{
        'all_news':all_news
    })
    
# Teachers page
def all_teachers(request):
    all_teachers=Teacher.objects.all()
    return render(request, 'all-teachers.html',{
        'all_teachers':all_teachers
    })
    
# Students page
def all_students(request):
    all_students=Student.objects.all()
    return render(request, 'all-students.html',{
        'all_students':all_students
    })


# Deatil Page
def detail(request,id):
    news=News.objects.get(pk=id)
    if request.method=='POST':
        name=request.POST['name']
        email=request.POST['email']
        comment=request.POST['message'] 
        Comment.objects.create(
            news=news,
            name=name,
            email=email,
            comment=comment
        )
    messages.success(request,'comment submitted but in moderation mode.')
    category=Category.objects.get(id=news.category.id)
    rel_news=News.objects.filter(category=category).exclude(id=id)
    comments=Comment.objects.filter(news=news,status=True).order_by('-id')
    return render(request, 'detail.html',{
        'news':news,
        'related_news':rel_news,
        'comments':comments
    })
    
def contact(request):
    if request.method=='POST':
        full_name=request.POST['full_name']
        email=request.POST['email']
        phone=request.POST['phone']
        title=request.POST['title']
        full_text=request.POST['full_text'] 
        Contact.objects.create(
            full_name=full_name,
            email=email,
            phone = phone,
            title=title,
            full_text=full_text
        )
        messages.success(request,'Contact submitted but in moderation mode.')
    return render(request, 'contact.html')

def faoliyat(request):
    return render(request, 'faoliyat.html')

def kafedra(request):
    return render(request, 'kafedra.html')

main/templates/all-news.html
{% extends 'base.html' %}
{% block content%}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">{{news.catgeory.title }}</h3>
	<!-- News Box -->

	{% for news in all_news %}

	<div class="card mb-4 shadow">
		<div class="row no-gutters">
			<div class="col-md-3">
				<img src="/media/{{news.image}}" class="card-img" alt="{{news.title}}">
			</div>
			<div class="col-md-8">
				<div class="card-body">
					<h5 class="card-title"><a href="/detail.html">{{news.title}}</a></h5>
					<p class="card-text">{{news.detail}}</p>
					<p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full
							<span>&rarr;</span></a></p>
				</div>
			</div>
		</div>
	</div>
	<style>
		img {
			float: left;

			width: 100%;
			padding: 20px 10px;
			padding-top: 20px;
			padding-right: 10px;
			padding-bottom: 20px;
			padding-left: 10px;
			display: block;
			object-fit: cover;

		}

		.col-md-3 {
			margin-bottom: 10px;
			float: left;
			height: 25rem;
		}

		.card {
			display: grid;
			width: 114rem;
			grid-gap: 6rem;
			grid-template-rows: repeat(auto-fit, minmax(30rem, 1fr));
			align-items: start;
		}

		.card .row {
			margin-right: 18%;
			background-color: #fff;
			border-radius: 0.4rem;
			overflow: hidden;
			box-shadow: 0 3rem 6rem rgba(0, 0, 0, 0.1);
			cursor: pointer;
			transition: 0.2s;
		}

		.card .row {
			margin-top: 10rem;
		}

		.row:hover {
			transform: translateY(-0.5%);
			box-shadow: 0 4rem 8rem rgba(0, 0, 0, 0.2);
		}

		.card-title {
			font-size: 3rem;
			font-weight: 500;
			color: #0d0d0d;
			margin-bottom: 1.5rem;
		}

		.btn {

			display: block;
			float: right;
			width: 30%;
			padding: 1.5rem;
			font-size: 1.4rem;
			text-align: center;
			color: #839ae4;
			background-color: #e6ecff;
			border: none;
			border-radius: 0.8rem;
			transition: 0.2s;
			cursor: pointer;
		}

		.btn span {
			margin-left: 1rem;
			transition: 0.2s;
		}

		.btn:hover,
		.btn:active {
			background-color: #6979b1;
			transition: 0.3 ease linear;
		}

		.btn:hover span,
		.btn:active span {
			margin-left: 1.5rem;
		}

		@media only screen and (max-width:715px) {
			.container {
				width: 715px;

			}

			.col-md-3 {
				width: 650px;
				height: 250px;
			}

			.container .row {
				display: flex;
				flex-direction: column;
			}

			.container .card {
				width: 650px;
				margin-left: 60px;
			}

			.container .col-md-8 h5 {
				font-size: 2rem;
			}

			.container .col-md-8 {
				margin-left: 1.1rem;
				margin-top: 15rem;
			}



			.card .row {
				box-shadow: none;
			}

			.container .btn {

				float: left;
				width: 200px;
			}

			.container h1 {

				font-size: 2.3rem;
				margin-left: 60px;
			}
		}
		@media only screen and (max-width:450px) {
			.container {
				width: 450px;

			}

			.col-md-3 {
				width: 380px;
				height: 250px;
			}

			.container .row {
				display: flex;
				flex-direction: column;
			}

			.container .card {
				width: 380px;
				margin-left: 60px;
			}

			.container .col-md-8 h5 {
				font-size: 2rem;
			}

			.container .col-md-8 {
				margin-left: 1.1rem;
				margin-top: 15rem;
			}



			.card .row {
				box-shadow: none;
			}

			.container .btn {

				float: left;
				width: 200px;
			}

			.container h1 {

				font-size: 2.3rem;
				margin-left: 60px;
			}
		}
	</style>
	{% endfor %}
</main>


{% endblock%}

main/templates/all-students.html
{% extends 'base.html' %}
{% block content%}

<!-- Page Header Start -->
<div class="container-fluid page-header py-5 mb-5">
	<div class="container py-5">
		<h1 class="display-3 text-white mb-3 animated slideInDown">Kafedra Haqida</h1>
		<nav aria-label="breadcrumb animated slideInDown">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a class="text-white" href="#">Asosiy</a></li>
				<li class="breadcrumb-item text-white active" aria-current="page">Talabalar</li>
			</ol>
		</nav>
	</div>
</div>
<style>
	.page-header {
		background: linear-gradient(to right bottom, rgb(24, 75, 176), rgba(29, 26, 191, 0.5), rgba(26, 191, 180, 0.5));
		background-size: cover;
	}
</style>
<!-- Page Header End -->


<!-- Testimonial Start -->
<div class="container-xxl py-5">
	<div class="container">
		<div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">
			<h1 class="text-primary">Iqtidorli Talabalar</h1>
		</div>
		{% for student in all_students %}
		<div class="owl-carousel testimonial-carousel wow fadeInUp" data-wow-delay="0.1s">
			<div class="testimonial-item text-center">
				<div class="testimonial-img position-relative">
					<img class="img-fluid rounded-circle mx-auto mb-5" src="/media/{{student.image}}">

				</div>
				<div class="testimonial-text text-center rounded p-4">
					<p>Til bilish darajasi: Rus tili, Ingliz tili</p>
					<p>Dasturlash mahorati: C++, Java</p>
					<p>Oʻrtacha ball : 4.47</p>
					<h5 class="mb-1">{{student.full_name}}</h5>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
<!-- Testimonial End -->

{% endblock%}

main/templates/all-teachers.html
{% extends 'base.html' %}
{% block content%}

<div class="container-fluid page-header py-5 mb-5">
	<div class="container py-5">
		<h1 class="display-3 text-white mb-3 animated slideInDown">Kafedra Haqida</h1>
		<nav aria-label="breadcrumb animated slideInDown">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a class="text-white" href="#">Asosiy</a></li>
				<li class="breadcrumb-item text-white active" aria-current="page">O'qtuvchilar</li>
			</ol>
		</nav>
	</div>
</div>
<style>
	.page-header {
		background: linear-gradient(to right bottom, rgb(24, 75, 176), rgba(29, 26, 191, 0.5), rgba(26, 191, 180, 0.5));
		background-size: cover;
	}
</style>
<!-- Page Header End -->


<!-- Team Start -->
<div class="container-xxl py-5">
	
	<div class="container">
		<div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">
			<h1 class="text-primary">O'qituvchilarimiz</h1>
		</div>
		<div class="row g-4">
			{% for teacher in all_teachers %}
			<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
				<div class="team-item rounded overflow-hidden">
					<div class="d-flex">
						<img class="img-fluid w-75" src="/media/{{teacher.image}}" alt="{{teacher.full_name}}" style="height: 280px;">
						<div class="team-social w-25">
							<a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i
									class="fab fa-facebook-f"></i></a>
							<a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i
									class="fab fa-twitter"></i></a>
							<a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i
									class="fab fa-instagram"></i></a>
						</div>
					</div>
					<div class="p-4">
						<h5>{{teacher.full_name}}</h5>
						<span>{{teacher.bio}}</span>
					</div>
				</div>
			</div>
			{% endfor %}

		</div>

	</div>
	
</div>

<!-- Team End -->

{% endblock%}

main/templates/detail.html
{% extends 'base.html' %}
{% block content%}
<div class="container-fluid page-header py-5 mb-5">
	<div class="container py-5">
		<h1 class="display-3 text-white mb-3 animated slideInDown">So'nggi yangiliklar</h1>
		<nav aria-label="breadcrumb animated slideInDown">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a class="text-white" href="/">Asosiy</a></li>
				<li class="breadcrumb-item text-white active" aria-current="page">Batafsil</li>
			</ol>
		</nav>
	</div>
</div>
<style>
	.page-header {
		background: linear-gradient(to right bottom, rgb(24, 75, 176), rgba(29, 26, 191, 0.5), rgba(26, 191, 180, 0.5));
		background-size: cover;
	}
</style>
<!-- Page Header End -->
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<style>
		@media(max-width:700px){
			.row-my-3{
				display: flex;
				flex-direction: column;
			}
			.row-my-3 .col-md-3{
				margin-left: 0 !important;
			}
		}
	</style>
	<div class="row-my-3" style="display: flex;">
		<!-- Left -->
		<div class="col-md-8 col-lg-8">
			<div class="card mb-3">
				<img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<hr />
					<p class="card-text">{{news.detail}}</p>
				</div>
				<div class="card-footer">
					In {{news.category.title}}
				</div>
			</div>



		</div>
		<!-- Related News -->
		<div class="col-md-3 col-lg-3" style="margin-left: 2rem;">
			<h3 class="mb-3 border-bottom pb-1">So'nggi Yangiliklar</h3>
			<!-- Category Box -->
			{% for news in related_news %}
			<div class="card mb-3 shadow">
				<img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<hr />
					<p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Batafsil</a></p>
				</div>
			</div>


			{% endfor %}
		</div>
	</div>
</main>
{% endblock%}

main/templates/home.html
{% extends 'base.html' %}
{% block content%}




<div class="container-fluid p-0 pb-5 wow fadeIn" data-wow-delay="0.1s">
	<div class="owl-carousel header-carousel position-relative">
		<div class="owl-carousel-item position-relative" data-dot="<img src='/media/img/tuit_slide_one.jpg'>">
			<img class="img-fluid" src="/media/img/tuit_slide_one.jpg" alt="">
			<div class="owl-carousel-inner">
				<div class="container">
					<div class="row justify-content-start">

					</div>
				</div>
			</div>
		</div>
		<div class="owl-carousel-item position-relative" data-dot="<img src='/media/img/tuit_slide_two.jpg'>">
			<img class="img-fluid" src="/media/img/tuit_slide_two.jpg" alt="">
			<div class="owl-carousel-inner">
				<div class="container">
					<div class="row justify-content-start">

					</div>
				</div>
			</div>
		</div>
		<div class="owl-carousel-item position-relative" data-dot="<img src='/media/img/tuit_slide_four.jpg'>">
			<img class="img-fluid" src="/media/img/tuit_slide_four.jpg" alt="">
			<div class="owl-carousel-inner">
				<div class="container">
					<div class="row justify-content-start">

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container-xxl py-5">
	<div class="container">
		<div class="row g-5">
			<div class="col-md-6 col-lg-3 wow fadeIn" data-wow-delay="0.1s">
				<div class="d-flex align-items-center mb-4">
					<div class="btn-lg-square bg-primary rounded-circle me-3">
						<i class="fa fa-graduation-cap text-white"></i>
					</div>
					<h1 class="mb-0" data-toggle="counter-up">3453</h1>
				</div>
				<h5 class="mb-3">Magistr talabalar</h5>
			</div>
			<div class="col-md-6 col-lg-3 wow fadeIn" data-wow-delay="0.3s">
				<div class="d-flex align-items-center mb-4">
					<div class="btn-lg-square bg-primary rounded-circle me-3">
						<i class="fa fa-graduation-cap text-white"></i>
					</div>
					<h1 class="mb-0" data-toggle="counter-up">4234</h1>
				</div>
				<h5 class="mb-3">Bakalavr talabalar</h5>
			</div>
			<div class="col-md-6 col-lg-3 wow fadeIn" data-wow-delay="0.5s">
				<div class="d-flex align-items-center mb-4">
					<div class="btn-lg-square bg-primary rounded-circle me-3">
						<i class="fa fa-users text-white"></i>
					</div>
					<h1 class="mb-0" data-toggle="counter-up">267</h1>
				</div>
				<h5 class="mb-3">O'qituvchilar</h5>
			</div>
			<div class="col-md-6 col-lg-3 wow fadeIn" data-wow-delay="0.7s">
				<div class="d-flex align-items-center mb-4">
					<div class="btn-lg-square bg-primary rounded-circle me-3">
						<i class="fa fa-briefcase text-white"></i>
					</div>
					<h1 class="mb-0" data-toggle="counter-up">47</h1>
				</div>
				<h5 class="mb-3">Hamkorlar</h5>

			</div>
		</div>
	</div>
</div>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css"
	integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous" />

<div class="container-fluid bg-light overflow-hidden my-5 px-lg-0">
	<div class="container about px-lg-0">
		<div class="row g-0 mx-lg-0">
			<div class="col-lg-6 ps-lg-0 wow fadeIn" data-wow-delay="0.1s" style="min-height: 400px;">
				<div class="position-relative h-100">
					<img class="position-absolute img-fluid w-100 h-100" src="/media/img/rektor.jpg"
						style="object-fit: cover;" alt="">
				</div>
			</div>
			<div class="col-lg-6 about-text py-5 wow fadeIn" data-wow-delay="0.5s">
				<div class="p-lg-5 pe-lg-0">
					<h6 class="text-primary" style="font-size: 2rem; margin-bottom: 2rem;">Biz haqimizda</h6>
					<p>"Multimedia texnologiyalari” kafedrasi Toshkent axborot texnologiyalari
						universiteti Ilmiy Kengashining
						(2011-yil 27-oktabrda 3(609) son bayoni) qarorini amalga oshirish maqsadida Toshkent axborot
						texnologiyalari
						universitetining 21.11.11 dagi 1070-sonli buyrug‘i asosida tashkil etildi.

						"Multimedia texnologiyalari” kafedrasiga biriktirilgan "Multimedia injiniringi” yo‘nalishi
						bo‘yicha har
						yili
						100 ga yaqin bakalavr talabalarining bitiruv oldi amaliyoti, ishlab chiqarish amaliyoti va
						o‘quv
						amaliyotlari tashkil etiladi. Kafedrada profesor-o‘qituvchilarining rahbarligida 50 ga yaqin
						bakalavrlik
						bitiruv malakaviy hamda 10 ga yaqin magistrlik ilmiy dissertatsiyalari himoya qilinadi.</p>
					<p><i class="fa fa-user text-primary me-3"></i>Kafedra mudiri: Nazirova Elmira Shodmonovna</p>
					<p><i class="fa fa-clock text-primary me-3"></i>Ish vaqti: Dushanba-Shanba (15:00-17:00)</p>
					<p><i class="fa fa-phone-alt text-primary me-3"></i>Tel: (0 371) 238-65-99</p>
					<p><i class="fa fa-envelope text-primary me-3"></i>Email: e.nazirova@tuit.uz</p>
					<a href="/kafedra" class="btn btn-primary rounded-pill py-3 px-5 mt-3">Batafsil</a>
				</div>
			</div>
		</div>
	</div>
</div>



<div class="container-xxl py-5">
	{% for category in three_categories %}
	<div class="container">
		<div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">
			<h1 class="text-primary">So'nggi Yangiliklar</h1>
		</div>
		<div class="row g-4">
			{% for news in category.news_set.all %}
			{% if forloop.counter < 5 %}
			<div class="col-md-6 col-lg-4 wow fadeInUp" data-wow-delay="0.1s">
				<div class="service-item rounded overflow-hidden">
					<img class="img-fluid" src="/media/{{news.image}}" alt="{{news.title}}" style="height: 250px; width: 400px;object-fit: cover;">
					<div class="position-relative p-4 pt-0">

						<h4 class="my-3">{{news.title}}</h4>
						<!-- <p>Biz quyosh va qayta tiklanadigan energiya sanoatining yutimizda
							rivojlantiramiz</p> -->
						<a class="small fw-medium" href="/detail/{{news.id}}">Batafsil<i
								class="fa fa-arrow-right ms-2"></i></a>
					</div>
				</div>
			</div>
			{% endif %}
			{% endfor %}

		</div>
		{% endfor %}
	</div>
</div>




<!-- Team Start -->
<div class="container-xxl py-5">
	<div class="container">
		<div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">
			<h1 class="text-primary">Tajribali O'qituvchilar</h1>
		</div>
		<div class="row g-4">
			<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
				<div class="team-item rounded overflow-hidden">
					<div class="d-flex">
						<img class="img-fluid w-75" src="/media/img/author-image1.jpg" alt="">
						<div class="team-social w-25">
							<a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i
									class="fab fa-facebook-f"></i></a>
							<a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i
									class="fab fa-twitter"></i></a>
							<a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i
									class="fab fa-instagram"></i></a>
						</div>
					</div>
					<div class="p-4">
						<h5>Sohibov Anvar</h5>
						<span>Mobil dasturlash o'qituvchisi</span>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
				<div class="team-item rounded overflow-hidden">
					<div class="d-flex">
						<img class="img-fluid w-75" src="/media/img/author-image2.jpg" alt="">
						<div class="team-social w-25">
							<a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i
									class="fab fa-facebook-f"></i></a>
							<a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i
									class="fab fa-twitter"></i></a>
							<a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i
									class="fab fa-instagram"></i></a>
						</div>
					</div>
					<div class="p-4">
						<h5>Odilova Nargiza</h5>
						<span>Mobil dasturlash o'qituvchisi</span>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
				<div class="team-item rounded overflow-hidden">
					<div class="d-flex">
						<img class="img-fluid w-75" src="/media/img/author-image3.jpg" alt="">
						<div class="team-social w-25">
							<a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i
									class="fab fa-facebook-f"></i></a>
							<a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i
									class="fab fa-twitter"></i></a>
							<a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i
									class="fab fa-instagram"></i></a>
						</div>
					</div>
					<div class="p-4">
						<h5>Karimova Madina</h5>
						<span>Mobil dasturlash o'qituvchisi</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Team End -->


<!-- Testimonial Start -->
<div class="container-xxl py-5">
	<div class="container">
		<div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">
			<h1 class="text-primary">Iqtidorli Talabalar</h1>
		</div>
		<div class="owl-carousel testimonial-carousel wow fadeInUp" data-wow-delay="0.1s">
			<div class="testimonial-item text-center">
				<div class="testimonial-img position-relative">
					<img class="img-fluid rounded-circle mx-auto mb-5" src="/media/img/testimonial-1.jpg">

				</div>
				<div class="testimonial-text text-center rounded p-4">
					<p>Til bilish darajasi: Rus tili, Ingliz tili</p>
					<p>Dasturlash mahorati: C++, Java</p>
					<p>Oʻrtacha ball : 4.47</p>
					<h5 class="mb-1">Daliyeva Iroda Ikrom qizi</h5>
				</div>
			</div>
			<div class="testimonial-item text-center">
				<div class="testimonial-img position-relative">
					<img class="img-fluid rounded-circle mx-auto mb-5" src="/media/img/testimonial-2.jpg">

				</div>
				<div class="testimonial-text text-center rounded p-4">
					<p>Til bilish darajasi: Rus tili, Ingliz tili</p>
					<p>Dasturlash mahorati: C++, Java</p>
					<p>Oʻrtacha ball : 4.47</p>
					<h5 class="mb-1">Qodirov Davron Inom o'gli</h5>
				</div>
			</div>
			<div class="testimonial-item text-center">
				<div class="testimonial-img position-relative">
					<img class="img-fluid rounded-circle mx-auto mb-5" src="/media/img/testimonial-3.jpg">

				</div>
				<div class="testimonial-text text-center rounded p-4">
					<p>Til bilish darajasi: Rus tili, Ingliz tili</p>
					<p>Dasturlash mahorati: C++, Java</p>
					<p>Oʻrtacha ball : 4.47</p>
					<h5 class="mb-1">Inomov Umarjon Qosim o'gli</h5>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Testimonial End -->
{% endblock%}